version: "3"
services:
  frontend:
    image: "frontend-service:snapshot1"
    ports:
      - "5000:80"
    depends_on:
      - mongo
    expose:
      - 5000
  backend:
    image: "notes-service:snapshot1"
    ports:
      - "5001:5000"
    depends_on:
      - mongo
      - frontend
    expose:
      - 5001
  mlops:
    image: "ml-ops:snapshot1"
    ports:
      - "5002:5000"
    depends_on:
      - mongo
      - frontend
      - backend
    expose:
      - 5002
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    expose:
      - 27017